"""Gate evidence and mention scanner regressions, without a companion."""

import re
import sys
from pathlib import Path

import pytest

from cc_tandem.verify import REVIEW_CHECKLIST, rerun_checks, scan_assistant_mentions


def test_gate_results_are_actual_and_continue_after_failure(tmp_path: Path) -> None:
    results = rerun_checks(
        [
            [sys.executable, "-c", "import sys; print('failed'); sys.exit(7)"],
            [sys.executable, "-c", "import sys; print('ok'); print('warning', file=sys.stderr)"],
            "printf shell > evidence.txt",
        ],
        cwd=tmp_path,
    )
    assert [result.returncode for result in results] == [7, 0, 0]
    assert not results[0].passed
    assert results[0].stdout == "failed\n"
    assert results[1].passed
    assert results[1].stderr == "warning\n"
    assert (tmp_path / "evidence.txt").read_text() == "shell"


def test_timeout_preserves_partial_output_and_launch_failure() -> None:
    results = rerun_checks(
        [
            [sys.executable, "-c", "import time; print('started', flush=True); time.sleep(10)"],
            ["/nonexistent-verification-command"],
        ],
        timeout=0.1,
    )
    assert results[0].timed_out and not results[0].passed
    assert results[0].stdout == "started\n"
    assert results[1].returncode is None and results[1].stderr
    assert not results[1].passed


@pytest.mark.parametrize("commands", ["make check", [""], ["  "], [[]]])
def test_invalid_gate_commands(commands: list[str] | list[list[str]] | str) -> None:
    with pytest.raises(ValueError):
        rerun_checks(commands)


@pytest.mark.parametrize("timeout", [0, -1])
def test_invalid_timeout(timeout: float) -> None:
    with pytest.raises(ValueError):
        rerun_checks([], timeout=timeout)


def test_empty_checks_and_no_timeout() -> None:
    assert rerun_checks([]) == ()
    assert rerun_checks([[sys.executable, "-c", "pass"]], timeout=None)[0].passed


@pytest.mark.parametrize("text", ["Generated with Codex", "written by CLAUDE", "codex-helper"])
def test_plain_mentions(text: str) -> None:
    assert len(scan_assistant_mentions(text)) == 1


def test_diff_only_added_lines_with_file_line_numbers() -> None:
    diff = (
        "diff --git a/file.py b/file.py\n--- a/file.py\n+++ b/file.py\n"
        "@@ -2,3 +2,4 @@\n Codex old context\n-Claude removed\n"
        "+# Generated by Codex\n+# +++ Claude\n unchanged\n"
        "diff --git a/other.py b/other.py\n--- a/other.py\n+++ b/other.py\n"
        "@@ -0,0 +1 @@\n+claude helper\n"
    )
    findings = scan_assistant_mentions(diff)
    assert [(item.source, item.line, item.mention) for item in findings] == [
        ("file.py", 3, "Codex"),
        ("file.py", 4, "Claude"),
        ("other.py", 1, "claude"),
    ]


def test_urls_project_name_substrings_and_configurable_allowlist() -> None:
    own_name = [r"(?i)\bcc-codex-tandem\b"]
    assert (
        scan_assistant_mentions(
            "https://example.invalid/codex git@example.invalid:claude cc-codex-tandem codextra",
            allowlist=own_name,
        )
        == ()
    )
    assert scan_assistant_mentions("import codex_sdk")
    assert scan_assistant_mentions("codex dependency", allowlist=[r"codex dependency"]) == ()
    findings = scan_assistant_mentions("https://example.invalid/codex Generated by Claude")
    assert [item.mention for item in findings] == ["Claude"]
    assert scan_assistant_mentions("cc-codex-tandem", allowlist=[])
    with pytest.raises(re.error, match="unterminated"):
        scan_assistant_mentions("", allowlist=["["])


def test_lock_dependencies_allowlisted_but_attribution_is_not(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text('name = "codex"\n# Generated by Claude\n')
    findings = scan_assistant_mentions(lock)
    assert len(findings) == 1 and findings[0].line == 2
    diff = '+++ b/package-lock.json\n@@ -0,0 +1 @@\n+"claude": {"version": "1"}\n'
    assert scan_assistant_mentions(diff) == ()
    ordinary = tmp_path / "app.py"
    ordinary.write_text('name = "codex"\n')
    assert scan_assistant_mentions([ordinary])


def test_repo_readme_and_manifests_have_zero_findings() -> None:
    root = Path(__file__).resolve().parents[2]
    paths = [root / "README.md", *sorted((root / ".claude-plugin").glob("*.json"))]
    assert scan_assistant_mentions(paths) == ()


def test_product_docs_do_not_hide_attribution(tmp_path: Path) -> None:
    readme = tmp_path / "README.md"
    readme.write_text("# cc-codex-tandem\nClaude plans, Codex builds\nGenerated by Codex\n")
    assert [item.line for item in scan_assistant_mentions(readme)] == [3]
    readme.write_text("# Another project\nCodex wrote this\n")
    assert scan_assistant_mentions(readme)


def test_metadata_is_scanned_even_with_empty_diff() -> None:
    findings = scan_assistant_mentions(
        "",
        commit_messages=["Change\nCo-Authored-By: Claude", "Generated by Codex"],
        branch_names=["feature/codex-implementation", "cc-codex-tandem"],
        allowlist=[r"(?i)\bcc-codex-tandem\b"],
    )
    assert [(item.source, item.line) for item in findings] == [
        ("commit-message[1]", 2),
        ("commit-message[2]", 1),
        ("branch[1]", 1),
    ]


def test_checklist_separates_intent_from_conformance_and_records_ticket_defects() -> None:
    assert any("right behaviour" in item for item in REVIEW_CHECKLIST)
    assert any("conformance separately" in item for item in REVIEW_CHECKLIST)
    assert any("ticket defects" in item and "BACKLOG.md" in item for item in REVIEW_CHECKLIST)


def test_scoped_lock_names_only_exempt_the_dependency_span(tmp_path: Path) -> None:
    lock = tmp_path / "package-lock.json"
    lock.write_text('"@vendor/codex-cli": {"note": "claude"}\n')
    assert [item.mention for item in scan_assistant_mentions(lock)] == ["claude"]
    lock = tmp_path / "uv.lock"
    lock.write_text('name = "claude-code"\n')
    assert scan_assistant_mentions(lock) == ()


def test_manifest_author_is_not_product_documentation(tmp_path: Path) -> None:
    directory = tmp_path / ".claude-plugin"
    directory.mkdir()
    manifest = directory / "plugin.json"
    manifest.write_text(
        '{\n"name": "cc-codex-tandem",\n"description": "Claude plans, Codex builds",\n'
        '"author": {"name": "Codex"}\n}\n'
    )
    assert [item.line for item in scan_assistant_mentions(manifest)] == [4]


def test_scanner_is_portable_across_repositories(tmp_path: Path) -> None:
    """No project name is hard coded, so the scanner works in any repository."""
    doc = tmp_path / "AGENTS.md"
    doc.write_text("This project drives Codex from Claude Code.\n")
    assert scan_assistant_mentions([doc], project_docs=("AGENTS.md",)) == ()


def test_attribution_is_reported_even_inside_a_project_document(tmp_path: Path) -> None:
    doc = tmp_path / "README.md"
    doc.write_text("A Claude Code plugin.\nCo-Authored-By: Claude <x>\n")
    findings = scan_assistant_mentions([doc], project_docs=("README*",))
    assert [f.line for f in findings] == [2]


def test_diff_applies_the_project_document_rule_per_file() -> None:
    """A ticket edit to the backlog must not drown real findings in noise."""
    diff = (
        "diff --git a/BACKLOG.md b/BACKLOG.md\n+++ b/BACKLOG.md\n@@ -1 +1,2 @@\n"
        "+Run tickets through Codex in parallel lanes.\n"
        "diff --git a/src/app.py b/src/app.py\n+++ b/src/app.py\n@@ -1 +1,2 @@\n"
        "+# built with Claude\n"
    )
    assert [(f.source, f.mention) for f in scan_assistant_mentions(diff)] == [
        ("src/app.py", "Claude")
    ]


def test_nested_project_documents_match_by_suffix() -> None:
    diff = (
        "diff --git a/docs/AGENT-LOG.md b/docs/AGENT-LOG.md\n+++ b/docs/AGENT-LOG.md\n"
        "@@ -1 +1,2 @@\n+Run the queue through Codex.\n"
    )
    assert scan_assistant_mentions(diff) == ()
